scan:
  skip-dirs:
    - "**/.git/**"
    - "**/tests/**"
    - "**/test/**"
    - "**/__pycache__/**"
    - "**/node_modules/**"
    - "**/build/**"
    - "**/dist/**"
    
  file-patterns:
    - "*.py"
    - "*.js"
    - "*.jsx"
    - "*.ts"
    - "*.tsx"
    - "*.json"
    - "*.lock"
    - "*.yaml"
    - "*.yml"
    - "requirements.txt"
    - "package.json"
    
vulnerability:
  ignore-unfixed: true
  severity:
    - HIGH
    - CRITICAL

secret:
  disable-entropy-check: true
